---
name: "Version Stamp Release"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    name: Build
    if: github.event_name == 'push' && contains(toJson(github.event.commits),
      '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci
      skip]') == false && contains(toJson(github.event.commits), '[skip ci]') ==
      false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # pin@v2.5.0 https://github.com/actions/checkout/commit/e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          fetch-depth: 0
  prerelease:
    needs: build
    name: Create Prerelease
    environment:
      name: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # pin@v2.5.0 https://github.com/actions/checkout/commit/e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          fetch-depth: 0
      - name: "Create prerelease version string"
        id: create_version
        uses: paulhatch/semantic-version@3d2ea28b25c9a892b07cd24b5675300b701fcef5 # pin@v4.0.3 https://github.com/PaulHatch/semantic-version/commit/3d2ea28b25c9a892b07cd24b5675300b701fcef5
        with:
          branch: "main"
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}-prerelease${increment}"
          # change_path: "src/my-service"
          short_tags: false
          bump_each_commit: false
      - name: "Apply tag"
        id: apply_tag
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # pin@v1.1.4 https://github.com/actions/create-release/commit/0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.create_version.outputs.version }}
          release_name: Release ${{ steps.create_version.outputs.version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: true
  release:
    name: Create Release
    needs: prerelease
    runs-on: ubuntu-latest
    environment:
      name: Release
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # pin@v2.5.0 https://github.com/actions/checkout/commit/e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          fetch-depth: 0
      - name: "Create release version string"
        id: create_version
        uses: paulhatch/semantic-version@3d2ea28b25c9a892b07cd24b5675300b701fcef5 # pin@v4.0.3 https://github.com/PaulHatch/semantic-version/commit/3d2ea28b25c9a892b07cd24b5675300b701fcef5
        with:
          branch: "main"
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          # change_path: "src/my-service"
          short_tags: false
          bump_each_commit: false
      - name: "Apply tag"
        id: apply_tag
        uses: actions/create-release@00cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # pin@v1.1.4 https://github.com/actions/create-release/commit/0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.create_version.outputs.version }}
          release_name: Release ${{ steps.create_version.outputs.version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false